# Generated by Django 3.0.8 on 2021-02-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('ONLINE_SERVICE', 'online_service'), ('TRAVEL', 'travel'), ('FOOD', 'food'), ('RENT', 'rent'), ('OTHER', 'other')], max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
