# Generated by Django 3.0.8 on 2021-02-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_expenses', '0002_expense_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
    ]
